name: Docker Image Auto Release

on:
  schedule:
    # Set a schedule to check for changes, e.g., every day
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Input version
        required: true
      tag:
        type: string
        description: Input tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: image/seafile_11.0
          build-args: |
            "SEAFILE_VERSION=${{ github.event.inputs.version }}"
          push: true
          tags: aitbase/seafile:${{ github.event.inputs.tag || github.event.inputs.version }}